version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    restart: always
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Gpdn2016
    volumes:
      - 'keycloak_data:/keycloak'
volumes:
  keycloak_data:
    driver: local